----
title:" This is a Blog Post"
date: 2018-12-14
----

title: May learns code.
author: Maymaymay
email: maymaymay@may.com
description: > # this means to ignore newlines until "baseurl:"
a non coder ready to join the octoverse

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
